### ISSUE TITLE
Make toughts categories an object instead of array

### ISSUE THREAD

**Issue by marcusnielsen** [nirajpandkar/thought-of-the-day#10]
I think it might be good to have the categories-section https://github.com/nirajpandkar/thought-of-the-day/blob/master/src/thoughts.json#L2 as an object instead of an array:
```
"categories":{
    "startup": "startup",
    "anonymous": "anonymous",
    "motivation": "motivation"
  },
```

This will change the usage to be reference-based instead of a string that can be misspelled.

Suggested usage should then be:
```
var anotherRandom = lib.random(lib.categories.anonymous);
```

Tell me if it goes in line with your vision, and I can try to make a pull request. And feel free to disregard the suggestion! It's your code :-)

**Comment by nirajpandkar** [comment]
First of all, thank you for taking interest in the project!
Now regarding the issue, I really like your perspective and I also thought about the benefit you stated - 

> This will change the usage to be reference-based instead of a string that can be misspelled.

But I personally think a _string_ provided as a parameter would be more **user-friendly**. Also the user won't need to think about the internal json structure to reference a category.

As much as I would like a PR at this point of time, but I would have to pass. If you have any other changes, I would totally love to hear them. :+1:

**Comment by nirajpandkar** [comment]
Closed it by mistake. I am still open for discussion if you could convince me otherwise.

**Comment by marcusnielsen** [comment]
No sweat! That is a valid point of view :-)

Here's another small library that uses "enums" instead: http://redux.js.org/docs/basics/Actions.html

But anyhow, I just saw your question on Kent's AMA, and wanted to show some support. Just making an issue feels good enough for me :-)

I think you should not feel convinced until you find a need for this fix. Otherwise you aren't solving your problems/pains, but just doing over-architectural coding.

Let's close this issue, and you can keep it in your mind if you run into some small problem with strings further ahead.

Cheers!

**Comment by nirajpandkar** [comment]
Thank you so much for understanding! Really appreciate the support :+1:

**Comment by marcusnielsen** [comment]
No problem!
