### ISSUE TITLE
No documentation for API

### ISSUE THREAD

**Issue by APratham** [nirajpandkar/thought-of-the-day#11]
Kindly share examples of how to use the API as it will be helpful for people who are looking at the repo for the first time. Can share use case if you want

**Comment by nirajpandkar** [comment]
Hi! You can find usage of the API documented in the README. Direct link here - https://github.com/nirajpandkar/thought-of-the-day#usage

**Comment by APratham** [comment]
I was referring to this: https://github.com/nirajpandkar/thought-of-the-day#api

But anyway, I have got it up and running. I still have few suggestions. 
If I am satisfied with what I have done, I won't pull it down and you can still access it here: https://quote-readme-3oseh3xclq-uc.a.run.app
1. As you have told in #9, the random function is not random and sometimes the same thought is also given all the time. Is there a way to fix that? 
2. How do I add my own list of thoughts/quotes etc?

**Comment by nirajpandkar** [comment]
Oh! Were you talking about a live demo for the API? I built this [Chrome Extension](https://chrome.google.com/webstore/detail/thought-of-the-new-tab/kglckaankcegmnohfnpgolmhnapnjjkn) using the same API, which kind of serves as a demo for the API.

But I see you have deployed it on a cloud. That's pretty cool too! It returns only one quote for now, it seems, though? If you're willing, you could add functionality to view quotes specifically from a particular [category](https://github.com/nirajpandkar/thought-of-the-day/blob/master/src/thoughts.json#L2). Let me know what your ideas are for the app. I could add it in the README if it helps people understand the API even more.

1. Never really got to investigate more on the subject. If you get a chance to do it, please feel free to put in a pull request :)
2. [This JSON](https://github.com/nirajpandkar/thought-of-the-day/blob/master/src/thoughts.json) holds all the thoughts and quotes which the API spits out. You can add yours in the same format to the existing file.

**Comment by APratham** [comment]
Yes. I built it in a way so that I can have it show one quote at a time. I wanted to use it as a fact generator kind of thing. So in a GitHub README, you will add facts. I wanted this to be an app which I can deploy and it can then give me random facts. 

This may help you to understand what I mean: https://github.com/shravan20/github-readme-quotes#follow-the-steps-to-provide-your-own-custom-quotes. The problem with this is that it has a card layout which I don't want. I just want it to have simple 1-2 lines at output.

For this, I needed to deploy your app on cloud which I managed to do after few tries. The other thing is trying to have custom quotes/facts. Do you think it's possible? If yes then I would be able to accomplish what is needed. Then I can update your README to include my use case for others.

**Comment by APratham** [comment]
By custom I mean that any user should be able to use their own list of quotes and facts

**Comment by nirajpandkar** [comment]
You can definitely have your own facts/quotes. As I said earlier, [this JSON file](https://github.com/nirajpandkar/thought-of-the-day/blob/master/src/thoughts.json) dictates what the API throws out to the user. So modifying that to include your own facts will accomplish what you want.

**Comment by APratham** [comment]
I am sorry I didn't quite get what you meant. Do you want me to add my quotes to your list? Or you want me to deploy my service on the cloud by replacing your list. I tried to update the service with another list of ~5-6 quotes just to see if it changes, it looks like it doesn't as it is still pulling from npm directory and using that. Which goes on to say that even if I added my quotes to your list, it won't work until you update the package on npm. That is why it is best if you can implement functionality for users to add their own quotes

**Comment by APratham** [comment]
The link is the same. You can see that even though I changed the list while uploading, it is still using the old list only

**Comment by nirajpandkar** [comment]
So that will warrant some development on the API. I'll add that to my TODO list. I can only work on it next week though.

I have distanced myself from Javascript/Node since this library. But I think an alternative (without needing any development and even quicker) would be to navigate into your `node_modules` and try adding your facts to the `thoughts.json` file in the `thoughts` directory installed in there. If I'm not wrong, that will reflect in your app immediately.

Let me know if that works :)

**Comment by APratham** [comment]
@nirajpandkar That's exactly what I did earlier when I said that I have changed the list. I downloaded all your files and then changed the JSON file (https://github.com/APratham/thought-of-the-day/blob/main/thoughts.json). The application is still using the old one only which you have made.

**Comment by APratham** [comment]
Please let me know if there is anything that I can do to help

**Comment by nirajpandkar** [comment]
Hey @APratham! Had a pretty busy week. Now onto the issue. Why don't you try the thing I mentioned earlier? So please tell me if I'm getting this right - 

You have installed the `thoughts` library for your project (the website) on your laptop/cloud. There must be a `node_modules` directory that should've gotten created? If you navigate in there, you'll find the `thoughts` library installed amongst your other npm libraries. Navigate to the `thoughts.json` file _**over there**_ and try adding/changing the quotes in there. That should get reflected in your live application as well. Of course, this is a temporary fix, but it should at least work. 

Also, I don't know what kind of functionality you're going for, but the thought isn't changing on refreshing your website page. It's static right now. Now even if there is a pseudo-random functionality to this library, it doesn't stay static in any way. Maybe there's an implementation fallacy at your end that you might want to check out. In any case, as the thought on your site currently says - 

> Don't give up because things are hard, but work harder, when you think of giving up.

:) Let me know how this pans out. If you didn't understand what to do, feel free to ask.

**Comment by APratham** [comment]
@nirajpandkar No issues mate

I understood what you meant and tried it out. It isn't working. This is because there are a lot of parts you will have to change, ie. `.gitignore` will never allow you to upload `node_modules`, so I had to delete that. Thankfully you don't have a lot of dependencies otherwise sometimes uploading all modules can take hours also. But now I encountered another issue. Your `Dockerfile` and my core application logic also run `npm install` by default, so there is no way you can make them to stop doing that, or else it will think that something is off. That is why eventhough I changed the file as per your instructions, it will always use the previous one. So I think the only way this can be solved is kindly make an API for your application.

Also yes, the deployment as of now completely works as I desire it to, I just want to find a way to use my `thoughts.json` with it. I wanted it to refresh in like a day or so. I am not sure about the current cycle, but it is changing everytime. You can check that by opening the URL I sent in Incognito you will see a different thought over there :)

**Comment by nirajpandkar** [comment]
I see! It was worth a try though. And I agree about the node_modules not getting uploaded. I think the only thing remaining is integration of this feature into the API. 

Can you make a new issue and elaborate this functionality so that we have some documentation available from the get-go? Thanks for following up :)
